### ISSUE TITLE
ZFR - Pages and Product Backlog

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#11]
שים לב!
המשימה הזאת מתחלקת לשניים:

עבודה על מסמכי הוויקי ודף איטרציית האפס בוויקי הפרויקט
עבודה על האב טיפוס
שני החלקים הם להגשה עד לתאריך ה"אבן דרך הראשונה" ולכן חשוב להתחיל כבר לעבוד עליהם
במידה ויש לך שאלות או קשיים אנא תעלה אותם בפני שאר חברי הצוות כדי שנוכל לפתור אותם בהקדם.
כמובן שבמידה ולא נמצא פתרון כלל במהלך הסבב הנוכחי תוכל לציין זאת בתגובה למשימה זו וכך נוכל להמשיך ולעבוד על הבעיה בעתיד.
חשוב לאמר שהמשימה היא דינמית ולכן כדאי ואף רצוי לתייג את האנשים שעובדים על משימות קשורות לשלך
דבר נוסף:
כמו דיברנו בישיבה אנחנו מתחילים לעובד עם הענפים של הגיטהב ולכן פתחתי ענף לכל אחד מאיתנו בתבנית הבאה:
name-branch
שימי לב "דחיפה" יש לעשות רק לענף שלך
בסוף האיטרציה נבצע איחוד של כל הענפים

משימותיך לאיטרציה זו:

- עמודים:
כרגע צריך ליצור שלושה עמודים עיקריים, עמוד הבית, עמוד קטגוריות ועמוד "על עצמי"
את שלושתם צריך לקשר לסרגל שכבר נמצא באפליקציה כך שלחיצה על כל מקש תעביר את המשתמש לעמוד המתאים.

- רשימת מאפיינים:
רשימת מאפיינים כפי שמפורט כאן:
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj5-zfr.md#%D7%A8%D7%A9%D7%99%D7%9E%D7%AA-%D7%9E%D7%90%D7%A4%D7%99%D7%99%D7%A0%D7%99%D7%9D-%D7%A1%D7%99%D7%A4%D7%95%D7%A8%D7%99-%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9--product-backlog
את המאפיינים צריך לגזור בעיקר מסיפורי המשתמש שכתבנו ב
SRS
כמובן שאת כל נושא המשימות אני כבר עשיתי אז אתה פתור

**Comment by DavidDr90** [comment]
יצרת ממש מעברים בין הדפים, וכאשר עוברים בין לשוניות המערכת ממש טוענת דפים מחדש.
כדאי אולי למצוא דרך לעשות את המעבר כמו בוואטסאפ, שהמעבר בין הכרטיסיות חלק ולא טוען את הדף מחדש...

**Comment by rkotahat** [comment]
בעת יצירת בילד לצורך העלאה לfirebase מקבלים את הארורים הבאים: 

`[10:23:13]  build dev started ...
[10:23:13]  clean started ...
[10:23:13]  clean finished in 3 ms
[10:23:13]  copy started ...
[10:23:13]  deeplinks started ...
[10:23:13]  deeplinks finished in 45 ms
[10:23:13]  transpile started ...
[10:23:16]  template error, "C:\Academy\software-engeneering\Lets-Talk\src\pages
\home\categories.html": Error: ENOENT:
            no such file or directory, open 'C:\Academy\software-engeneering\Let
s-Talk\src\pages\home\categories.html'
[10:23:16]  transpile finished in 2.93 s
[10:23:16]  preprocess started ...
[10:23:16]  preprocess finished in 1 ms
[10:23:16]  webpack started ...
[10:23:16]  copy finished in 3.12 s
[10:23:21]  webpack finished in 4.42 s
[10:23:21]  sass started ...
Without `from` option PostCSS could generate wrong source map and will not find
Browserslist config. Set it to CSS file path or to `undefined` to prevent this w
arning.
[10:23:22]  sass finished in 802 ms
[10:23:22]  postprocess started ...
[10:23:22]  postprocess finished in 10 ms
[10:23:22]  lint started ...
[10:23:22]  build dev finished in 8.35 s
> ionic cordova prepare --no-build
> cordova prepare

You have been opted out of telemetry. To change this, run: cordova telemetry on.


[10:23:25]  tslint: ...oftware-engeneering/Lets-Talk/src/providers/category-serv
ice/category-service.ts, line: 26
            Duplicate variable: 'title'

      L25:  this.addCategory(new Category(title,url));
      L26:  var title = "MySelf";
      L27:  var url = "/assets/imgs/myself.png";

[10:23:25]  tslint: ...oftware-engeneering/Lets-Talk/src/providers/category-serv
ice/category-service.ts, line: 27
            Duplicate variable: 'url'

      L26:  var title = "MySelf";
      L27:  var url = "/assets/imgs/myself.png";
      L28:  this.addCategory(new Category(title,url));

[10:23:25]  tslint: C:/Academy/software-engeneering/Lets-Talk/src/pages/add-phra
se/add-phrase.ts, line: 4
            'CameraOptions' is declared but its value is never read.

       L3:  import { FormGroup, FormBuilder, Validators } from '@angular/forms';

       L4:  import { Camera, CameraOptions } from '@ionic-native/camera';

[10:23:25]  tslint: C:/Academy/software-engeneering/Lets-Talk/src/app/app.compon
ent.ts, line: 7
            All imports are unused.

       L6:  import { HomePage } from '../pages/home/home';
       L7:  import { AddPhrasePage } from '../pages/add-phrase/add-phrase';
       L8:  import { MockTestPage } from '../pages/mock-test/mock-test';

[10:23:25]  tslint: C:/Academy/software-engeneering/Lets-Talk/src/app/app.compon
ent.ts, line: 8
            All imports are unused.

       L7:  import { AddPhrasePage } from '../pages/add-phrase/add-phrase';
       L8:  import { MockTestPage } from '../pages/mock-test/mock-test';
       L9:  @Component({

[10:23:25]  tslint: C:/Academy/software-engeneering/Lets-Talk/src/pages/home/hom
e.ts, line: 1
            'Input' is declared but its value is never read.

       L1:  import { Component, Input, Output } from '@angular/core';
       L2:  import { NavController } from 'ionic-angular';

[10:23:25]  tslint: C:/Academy/software-engeneering/Lets-Talk/src/pages/home/hom
e.ts, line: 1
            'Output' is declared but its value is never read.

       L1:  import { Component, Input, Output } from '@angular/core';
       L2:  import { NavController } from 'ionic-angular';

[10:23:25]  tslint: C:/Academy/software-engeneering/Lets-Talk/src/pages/home/hom
e.ts, line: 3
            All imports are unused.

       L2:  import { NavController } from 'ionic-angular';
       L3:  import { CategoryServiceProvider } from '../../providers/category-se
rvice/category-service';
       L4:  import { Client } from '../../models/Client';

[10:23:25]  tslint: C:/Academy/software-engeneering/Lets-Talk/src/pages/home/hom
e.ts, line: 4
            All imports are unused.

       L3:  import { CategoryServiceProvider } from '../../providers/category-se
rvice/category-service';
       L4:  import { Client } from '../../models/Client';
       L5:  import { CategoriesPage } from '../categories/categories';

[10:23:25]  tslint: C:/Academy/software-engeneering/Lets-Talk/src/pages/home/hom
e.ts, line: 8
            All imports are unused.

       L7:  import { AboutMePage } from '../about-me/about-me';
       L8:  import { PhrasesPage } from '../phrases/phrases';
       L9:  import { AddPhrasePage } from '../add-phrase/add-phrase';

[10:23:25]  tslint: ...Academy/software-engeneering/Lets-Talk/src/components/my-
category/my-category.ts, line: 1
            'Output' is declared but its value is never read.

       L1:  import { Component, Input, Output } from '@angular/core';
       L2:  import { Category } from '../../models/Category';

[10:23:25]  tslint: ...Academy/software-engeneering/Lets-Talk/src/components/my-
category/my-category.ts, line: 3
            All imports are unused.

       L2:  import { Category } from '../../models/Category';
       L3:  import { CategoryServiceProvider } from '../../providers/category-se
rvice/category-service';
       L4:  import { Client } from '../../models/Client';
`

סיכום שלהם:
* [ ] **ארור** על גישה לקובץ שלא קיים - 'C:\Academy\software-engeneering\Let
s-Talk\src\pages\home\categories.html'
* [ ] וורנינגס על משתנים כפולים, אימפורטים לא רלוונטים

**Comment by AlexShimanovich** [comment]
errors and warnings fixed, navigation not yet

**Comment by AlexShimanovich** [comment]
Page navigation updated

**Comment by DavidDr90** [comment]
@AlexShimanovich 
it's seems that you fix the page nav, for the indro sliders there is another issue,
so can we close this one?

**Comment by AlexShimanovich** [comment]
all done here
