### ISSUE TITLE
ZFR - Phrase Component and Iter0 page in project Wiki

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#12]
שים לב!
המשימה הזאת מתחלקת לשניים:

עבודה על מסמכי הוויקי ודף איטרציית האפס בוויקי הפרויקט
עבודה על האב טיפוס
שני החלקים הם להגשה עד לתאריך ה"אבן דרך הראשונה" ולכן חשוב להתחיל כבר לעבוד עליהם
במידה ויש לך שאלות או קשיים אנא תעלה אותם בפני שאר חברי הצוות כדי שנוכל לפתור אותם בהקדם.
כמובן שבמידה ולא נמצא פתרון כלל במהלך הסבב הנוכחי תוכל לציין זאת בתגובה למשימה זו וכך נוכל להמשיך ולעבוד על הבעיה בעתיד.
חשוב לאמר שהמשימה היא דינמית ולכן כדאי ואף רצוי לתייג את האנשים שעובדים על משימות קשורות לשלך
דבר נוסף:
כמו דיברנו בישיבה אנחנו מתחילים לעובד עם הענפים של הגיטהב ולכן פתחתי ענף לכל אחד מאיתנו בתבנית הבאה:
name-branch
שימי לב "דחיפה" יש לעשות רק לענף שלך
בסוף האיטרציה נבצע איחוד של כל הענפים

משימותיך לאיטרציה זו:

- רכיב ביטוי:
תעבוד מול המפורט במסמך ה SDS
https://github.com/DavidDr90/Lets-Talk/wiki/Software-Design-Specification
שים לב שאתה בונה את המחלקה מכל הרכיבים הנדרשים
אל תשכח להוסיף "כוכב מועדפים" כמו שיש בג'ימיל
כמו כל הפונקציונאליות הנדרשת לרכיב שכזה

- פיתוח הסעיפים העיקריים בעמוד הוויקי של הסבב
https://github.com/DavidDr90/Lets-Talk/wiki/Iter-0---ZFR
בעיקר את הדברים הבאים:
  - Iteration Goals
  - Process, Methods & Tools

**Comment by DavidDr90** [comment]
אור שים לב! אני לא חושב שנכון תכנותית לגרום לתמונה ולמשפט להיות אחד ליד השני בעזרת ה css
עדיף פשוט לשים אותם בתוך טבלה בקובץ html
ככה גם אם המשתמש מחליף פלטפורמות התמונה לא "יוצאת" מהעיצוב כמו שקורה עכשיו...

**Comment by rkotahat** [comment]
התמונה יוצאת מהמסגרת בגלל באג במרג', הבילד לא נעשה כמו שצריך אבל העלאתי את
זה בכל זאת, וזה יעבוד עבור כל פלטפורמה.

בתאריך יום ב׳, 23 באפר' 2018, 8:28, מאת David Recanati ‏<
notifications@github.com>:

**Comment by DavidDr90** [comment]
איזה באג במרג'?

**Comment by rkotahat** [comment]
![image](https://user-images.githubusercontent.com/34075902/39112426-230f6362-46e1-11e8-85ee-00c108371ee6.png)
אני לא מצליח למצוא את המיקום, אבל יש כנראה אימפורט לקובץ שלא קיים

**Comment by ofekba** [comment]
אני אטפל בזה אחר כך ואדאג שזה ימוקם מוש כמו שהם ביקשו ובלי סטיות מהגבולות

**Comment by rkotahat** [comment]
זה לא יסטה מהגבולות אם הבילד יצליח כמו שצריך, כרגע הוא לא מצליח אז זה דופק הכל.
בלי קשר תשימו לב שההעברת עמודים לא פועלת בצורה טובה - אם עוברים מדף מסויים נפתח סשן חדש לדף אחר, ואז אם בוחרים בדף הראשי שוב נפתח סשן נוסף במקום לחזור לקודם.
למשל:
home-page -> categories -> home-page
יוצר שני עמודי בית חדשים במקום לעבור לאחד שקיים כבר.
#11

**Comment by DavidDr90** [comment]
נכון אלכס מטפל בז

**Comment by AlexShimanovich** [comment]
Page navigation updated

**Comment by DavidDr90** [comment]
@or2511 
alex fix his pages nav.
did you fix your phrase component?

**Comment by DavidDr90** [comment]
done
