### ISSUE TITLE
Iter1 - Google Image Search and Planing next Iteration

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#20]
We are starting the first iteration.
If you did not finish your last issue from the last iteration (iter0), please do ASAP!
Please read the meeting summaries, **before** you start your work, in the following link:
https://github.com/DavidDr90/Lets-Talk/wiki/Iter-0---ZFR#meeting-summaries

### Importent:
For the next iteration, including this one, each one of us need to contribute to the team work and the course team should be aware to that, so read the following link **carefully** and work by it.
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj6-iterations.md

## Your Tasks are:

1. Google Search:
You will make use a google Query to look for images on line.
In the "add phrase" prosse the user can choose to look online for image,
you should take the input text, if there is on, and send it to goolge for search
then, aftert the user pice his image we should get the image url to instore it on the user DB.

2. Wiki is on!
Planing the next iteration.
Please read all the text (  ;-) ) in this link:
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj6-iterations.md#1-%D7%AA%D7%9B%D7%A0%D7%95%D7%9F-%D7%94%D7%A1%D7%91%D7%91-%D7%94%D7%91%D7%90

**Comment by DavidDr90** [comment]
@AlexShimanovich 
I cann't find any code releated to this issue... did you push it to your branch?

**Comment by AlexShimanovich** [comment]
No its still broken, not commited this iteration

**Comment by AlexShimanovich** [comment]
image search is always in next iteration

**Comment by DavidDr90** [comment]
depricated
