### ISSUE TITLE
Iter1 - Welcome Slides

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#23]
We in the middle of the first iteration so the next task will be small and will give you some time to finish the past tasks...

As part of the client requirements we want to create the "about me" page dynamically for each user, therefor we the user open the app for the first time we will show him slides that offer him to signup (in the future) to the app and to create the "about me" page. 
The slides will guide the user to input the necessary fields for the "about me" page, of course the user can avoid and skip the slides process and add the info later.
The slide need to know that this is the first time the user open the app and in the end should create the "about me" page with the input information.

You can read more about the slides here:
- https://ionicframework.com/docs/api/components/slides/Slides/#
- https://www.youtube.com/watch?v=vCsdZD2KNAs#
- https://www.youtube.com/watch?v=3oqFc6qiE8k#

Please make sure to finish all the previous tasks by the end of the week... #11 & #20 
**If you need some help please let me know!**

**Comment by DavidDr90** [comment]
right now when we enter the app its open the login screen...
I think that we want the user to press on the "login" button to open the login screen...

from where this bug come from? @AlexShimanovich @or2511 @dor132133

**Comment by AlexShimanovich** [comment]
we did not integrate the login into my slides yet.
right now its an external popup that comes when you open the app if no user is logged in
there is a (click) on my first slide, we can use it to open the popup.
something is broken with the next slides but first slide works fine

**Comment by or2511** [comment]
There is a problem with the slides.
When the user tries to slide left or right only the first slide moves and then it gets stuck.

**Comment by DavidDr90** [comment]
We changed the intro method, now there is a landing page with login and then you move to the about me form page to fill the about me category. if the about me category is already full you go to the home page
