### ISSUE TITLE
Iter1 - Special Pages

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#24]
We in the middle of the first iteration so the next task will be small and will give you some time to finish the past tasks...

You will create the special pages like: Numbers, Calendar etc'... please look in the notebook and the cards that was provide from the Hadassa people... for now those pages can stand alone but in the future they will be under "category" component.

Please be in touch with the ladies in Hadassa and consult with them what the bast way to create this pages.

See the next two files:
- https://github.com/DavidDr90/Lets-Talk/blob/master/Wiki%20Stuff/TODO/%D7%A4%D7%A0%D7%A7%D7%A1%20%D7%90%D7%99%D7%AA%D7%9F%20%D7%A2%D7%91%D7%A8%D7%99%D7%AA.docx#
- https://github.com/DavidDr90/Lets-Talk/blob/master/Wiki%20Stuff/TODO/%D7%93%D7%A4%D7%99%D7%9D%20%D7%9E%D7%95%D7%9B%D7%9F2.pdf#

keep the code you push clean ;-)

P.S.:
*_Wiki task_* :add screenshots and MVP section to the first iteration wiki page:
https://github.com/DavidDr90/Lets-Talk/wiki/Iter1-MVP-Serve-Side

If you think that you finished the previous task please move them to the next stage in the project board #18

**Comment by ofekba** [comment]
added some default paged to the DB, created an[EXEL table](https://github.com/DavidDr90/Lets-Talk/blob/master/Wiki%20Stuff/%D7%AA%D7%9B%D7%95%D7%9C%D7%AADB.xlsx) that describe which phrases and categories I added to the DB, which of them has a photo the store in the storage.

**Comment by DavidDr90** [comment]
to be continued...
