### ISSUE TITLE
Iteration 1 - MVP - Server Side and DB

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#25]
# Iteration 1 - MVP - Server Side and DB
#### Related Issues
- [ ] #22 
- [ ] #18 
- [ ] #24  
- [ ] #20 
- [ ] #23 
- [ ] #19 

#### Checklist, e.g.,:
- [ ] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Code reviewes
  - [x] Client review
  - [x] Issues updates
  - [x] Section on application of course materials
- [ ] git tag
- [x] Next iteration:
  - [x] Open page
  - [ ] Select stories and plan issues
  - [ ] Test scenarios
- [ ] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

**Comment by robi-y** [comment]
- nice use of javadoc style documentation (please present in class)
