### ISSUE TITLE
Iter2 - Server Side, DB & Log-In

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#33]
In this iteration we will focus on finishing the DB and storage and the log-in process.
As part of this iteration we will make a code review, each one of us assigned to review another member's code, in iteration 2 wiki page you can find which one is yours. please make sure to review his code and add the link in the right spot.

### Importent:
For the next iteration, including this one, each one of us need to contribute to the team work and the course team should be aware of that, so read the following link **carefully** and work by it.
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj6-iterations.md

Like in the previous issues your task consists of two things, one for the wiki page and one for the app.

## Your tasks:
1. Finish the Storage and DB:
    a. Finish all the connection between the app and the firebase server and DB.
    b. Make the categories clickable, so if the user click on some category he will see a new page with the phrases and sub-category related to the parent category.
    c. Enable sub categories in the DB collection.
    d. write upload function that gets the form object (text, image path and audio file path) and save it on the storage and connect it to the DB.
    e. Create a loading window to be display when the app first open while the app load the data from the server. _Think on some smart way on when to stop the loading and move to the app_

2. Fix the log-in pop-up window:
The log-in windows should be display only after the user click on the log-in option in alex's slides.
**This task is last in our priorities, finish the 1st task and then move to the 2nd.**

3. Wiki page:
**Please fill the code review**

#### Related Issues/Tasks
- [x] #25 

### Testing:
**In this section we describe some testing that you can make to test your work**
- [x] Create a form object and try to upload it to the server.
- [x] Click on Category and see if the phrases related to this category are display.
- [x] Log in to some Gmail account and see if you get the categories and phrases related to this user.

**Comment by DavidDr90** [comment]
@or2511 @dor132133 
After some test on the log-in process here some insides, and bugs to fix:
1. In AutenticationProvider -> createAuthentication() you use the auth.signInWithPopup() method. This method does not work on mobile phones, after some reading you need to use auth.signInWithRedirect() insted.
2. In AboutMePage -> constructor, the line this.AsyncPhrasesloader(); is throwing the following exeption:
"Error: Uncaught (in promise): TypeError: Cannot read property 'subscribe' of undefined
TypeError: Cannot read property 'subscribe' of undefined". 
You should check if the aboutMeCategory is NOT undefine before you continue to the asycPhraseloader().
3. In storage -> uploadFile: this function should get a form object (text, imagePath and audioPath) and upload it to the storage, for now the function only upload files.

### Please fix this bugs **ASAP**!

**Comment by DavidDr90** [comment]
@or2511 
To clear the last section in my last comment (3)... you will get Phrase or Caegory varibale and need to upload that variable...

**Comment by DavidDr90** [comment]
@or2511 
follow this tutorial:
https://www.youtube.com/watch?v=6yGrLWq-oIo

maybe it will help with the upload storage....

**Comment by dor132133** [comment]
this issue is done
