### ISSUE TITLE
Iter3 - Sub Categories and Fix the DB

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#51]
In this iteration we will focus on adding a new feature to the app.
The "edit mode" provide the user the functionality of remove, edit, hide or make visible and rearange a phrase or category. Additionally we will finishing all the previuse issues that need to be done.
As part of this iteration we will make a refactoring to the working procces, each one of us will contribute to the refactoring section in i[teration 3 wiki page](https://github.com/DavidDr90/Lets-Talk/wiki/Iter3---Edit-Mode).

### Importent:
For the next iteration, including this one, each one of us need to contribute to the team work and the course team should be aware of that, so read the following link **carefully** and work by it.
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj6-iterations.md

## Your tasks:
1. Fix the DB:
Try to understand the Promise and how to use it. Catch the errors in the find() methods, and fix the "add and pull" from the DB when create a new phrase or category and then need to accsses the new object.
releted issues:
#33 
#19 

2. Sub Categories:
Has the client requested in each category there will be only one category name "משפטים", when the user add phrase he will dicide if the phrase is "משפט" or "שם עצם" if the phrase is "משפט" he will place in the sub category. The sub category should be always in the top of the perant category page.

3. Wiki Stuff:
Add the summary of the client meeting to the wiki page. You can use hebrew or english, please ask ofek who to do that.

### Testing:
**In this section we describe some testing that you can make to test your work**
- [x] Try to add phrase to the sub cateogry.
- [x] Delete the sub category.
- [x] Create a new phrase the is a "שם עצם" and check if it place in the sub category.

**Comment by DavidDr90** [comment]
For my issue I need you to create a new function name: "getSubCategoryID( parentCategoryID)"
This function get a category Id and return the id of the sub category (תת קטגוריה משפטים) of the input category.

**Comment by dor132133** [comment]
ok, notice that could be more then one subCategory, so the method will gets two params:
getSubCategoryID(subCategoryName, parentCategoryID);

 Is that good for you?

**Comment by DavidDr90** [comment]
its good.
By the way for the order functionnality I need a method that return the highset number in the order variable for the phrases in some category and for the categories in a specific user
