### ISSUE TITLE
Iter3 - Design and Order the Defaults

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#52]
In this iteration we will focus on adding a new feature to the app.
The "edit mode" provide the user the functionality of remove, edit, hide or make visible and rearange a phrase or category. Additionally we will finishing all the previuse issues that need to be done.
As part of this iteration we will make a refactoring to the working procces, each one of us will contribute to the refactoring section in i[teration 3 wiki page](https://github.com/DavidDr90/Lets-Talk/wiki/Iter3---Edit-Mode).

### Importent:
For the next iteration, including this one, each one of us need to contribute to the team work and the course team should be aware of that, so read the following link **carefully** and work by it.
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj6-iterations.md

## Your tasks:
1. Order the Defaults:
Has the client requested the defaults categories and phrases should be in a pre-define order, some fix the order to the defaults object. You can use the new order variable that dor and alex will add to the objects in the DB.
releted issues: #32   

2. App Design:
The client promise that he will delevire the colors for the app in this week, after we will recive the colors use them to design all the app. Please remember that the app will be an android or iOS app so design to this OS. 

### Testing:
**In this section we describe some testing that you can make to test your work**
- [x] Change the order in check if the UI changed.
- [x] Add category and check the order.
- [x] Check the new design on a different android devices.

**Comment by DavidDr90** [comment]
@ofekba Ofkilish!!!!
We need to ask the client what defualt image he want for the "משפטים" sub category

**Comment by ofekba** [comment]
finished this issue a week ago
