### ISSUE TITLE
Iter3 - Upgrade Add Page and Wiki Page

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#53]
In this iteration we will focus on adding a new feature to the app.
The "edit mode" provide the user the functionality of remove, edit, hide or make visible and rearange a phrase or category. Additionally we will finishing all the previuse issues that need to be done.
As part of this iteration we will make a refactoring to the working procces, each one of us will contribute to the refactoring section in i[teration 3 wiki page](https://github.com/DavidDr90/Lets-Talk/wiki/Iter3---Edit-Mode).

### Importent:
For the next iteration, including this one, each one of us need to contribute to the team work and the course team should be aware of that, so read the following link **carefully** and work by it.
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj6-iterations.md

## Your tasks:
1. Order the Defaults:
Upgrade the Add Phrase Page has the client requested. Add the option to choose a color to a category, add a toggle to dicide between "משפט" and "שם עצם". Change the NIKUDE key board.
releted issues: 
#35 
#22 

2. Wiki page:
Add text to the wiki page.

### Testing:
**In this section we describe some testing that you can make to test your work**
- [ ] Change the color of a category.
- [ ] Add a new "משפט" or "שם עצם".
- [ ] Check the new NIKUDE key borad.

**Comment by dor132133** [comment]
For my issue, I just neen you to **block** the access of "add new sub-category" from a sub-category's page.
(one level hierarchy)

**Comment by DavidDr90** [comment]
I blocked the add sub category option in one level sub category, has you requested.

**Comment by DavidDr90** [comment]
finish this issue
