### ISSUE TITLE
Iter4 - Finish Order and Last Wiki Page

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#66]
We are entering the final stage of our project. In this last iteration we will finish all the last issues and create user guide to the user. Additionally we will test our app in the real environment on android and iOS devices and fix the bugs.

## Your tasks:
1. **Dor's**: New Order When Add new Item:
Has we decided when the user add new category or new phrase it will present in the first place on the list, therefor we need to update the order field in all the other items. This should happen when we delete and item or rearrange the order in the list.
Related issues: 
#65
#52 
#53 

2. Wiki Page:
You need to add information to the iteration 4 wiki page. Please make sure you read the assignment page in the class repo in this link:
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj6-iterations.md#
**Please focus on the last section, number 6 sub section 5**
Link to our wiki page for this iteration is:
https://github.com/DavidDr90/Lets-Talk/wiki/Iter4---Deliver-the-App
#### In the Last presentation we will be tested on this page. Please give this task the full attention

3. Fix App Builder and Storage:
We receive a table from the client with all the categories, sub categories and phrases that should be in the app builder as default. In the last week of the course every one will have a small piece of the table that he is responsible to add to the app builder. 
In each item you add to the app builder there should be an image, if there is appropriate one on the storage, and an audio file generate from the TTS server.
Please connect Ofek on any question you have on the working with the app builder.
 
### Testing:
**In this section we describe some testing that you can make to test your work**
- [x] Remove a phrase from the list and check the order.
- [x] Add new phrase in the app and check the order.
- [x] Rearrange the sub categories and make sure the new order is in place.

**Comment by or2511** [comment]
Done with this issue.
@dor132133
