### ISSUE TITLE
ZFR - SCSS Style and User Manual

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Lets-Talk#9]
שים לב!
המשימה הזאת מתחלקת לשניים:

עבודה על מסמכי הוויקי ודף איטרציית האפס בוויקי הפרויקט
עבודה על האב טיפוס
שני החלקים הם להגשה עד לתאריך ה"אבן דרך הראשונה" ולכן חשוב להתחיל כבר לעבוד עליהם
במידה ויש לך שאלות או קשיים אנא תעלה אותם בפני שאר חברי הצוות כדי שנוכל לפתור אותם בהקדם.
כמובן שבמידה ולא נמצא פתרון כלל במהלך הסבב הנוכחי תוכל לציין זאת בתגובה למשימה זו וכך נוכל להמשיך ולעבוד על הבעיה בעתיד.
חשוב לאמר שהמשימה היא דינמית ולכן כדאי ואף רצוי לתייג את האנשים שעובדים על משימות קשורות לשלך
דבר נוסף:
כמו דיברנו בישיבה אנחנו מתחילים לעובד עם הענפים של הגיטהב ולכן פתחתי ענף לכל אחד מאיתנו בתבנית הבאה:
name-branch
שימי לב "דחיפה" יש לעשות רק לענף שלך
בסוף האיטרציה נבצע איחוד של כל הענפים

משימותיך לאיטרציה זו:

- עיצוב כללי לאפליקציה:
שימי לב שאנחנו עובדים עם קבצי 
SCSS
וגם שלאיוניק יש דרך שונה מאנגולר לעיצוב כללי של האפליקציה

- המשך עבודה על המדריך למשתמש
אלכס כבר יצר שלד בסיסי למדריך למשתמש, את השלד ניתן למצוא כאן:
https://github.com/DavidDr90/Lets-Talk/wiki/User-Manual
את ודור ממשיכים לפתח אותו הלאה
תחלקו ביניכם את העבודה כפי שכתובה כאן:
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj5-zfr.md#%D7%AA%D7%99%D7%A2%D7%95%D7%93-%D7%94%D7%9E%D7%95%D7%A6%D7%A8

**Comment by DavidDr90** [comment]
כדי להביא מה בדיוק המשימה:
המטרה שלך היא לבנות עיצוב כללי למערכת, העיצוב מוכל על כל רכיב וכל עמוד שיתווסף למערכת אלא אם כן יש לאותו רכבים או עמוד מפרט עיצוב שונה.
תקראי קצת בלינקים האלה:
- https://ionicframework.com/docs/theming/theming-your-app/
- https://www.joshmorony.com/a-guide-to-styling-an-ionic-2-application/
- https://medium.com/craft-academy/a-beginners-guide-on-how-to-style-an-ionic-2-mobile-app-dd7469c365af
- http://ionicframework.com/docs/theming/

הסרטון הבא מדבר בדיוק על זה, ממליץ לראות ולעקוב אחריו...
https://www.youtube.com/watch?v=CW7kvEJlNys

בכל מקרה את עיקר העיצוב את עושה בקובץ הזה:
https://github.com/DavidDr90/Lets-Talk/blob/master/src/theme/variables.scss

**Comment by DavidDr90** [comment]
העלתי את הקובץ עיצוב לענף המאסטר
כל הכבוד על העבודה במשימה הזאת!

**Comment by ofekba** [comment]
ביצעתי כומיט לקובץ SCSS:):):):):)
